# H2 Database Configuration for Testing
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=false

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-test.sql

# Server Configuration
server.port=8081

# Security JWT
security.jwt.key.private=9c9c48d57077710e8a8ec4a72f0c959fa11ea2c2e1073b7c7d39b4eefff5ddf8
security.jwt.user.generator=AUTH0JWT-BACKEND

